# Use root/example as user/password credentials
version: "3.1"

services:
  jupyter:
    container_name: jupyter
    image: interactive_analysis/jupyter_notebook:0.1.0-bullseye-x86_64 
    ports: 
      - 8888:8888
    volumes:
      - "$PWD/notebooks:/var/task/workspace"
      - "$PWD/resources/.secret:/tmp/.secret"
    networks:
      - backend
networks:
  backend:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
          gateway: 172.16.240.1
        - subnet: 2001:3984:3990::/64
          gateway: 2001:3984:3990::1    